### ISSUE TITLE
Install error on Windows

### ISSUE THREAD

**Issue by kewp** [resin-io/pinejs#213]
For some reason, bcrypt won't compile. Can I upgrade it to the latest, or safely ignore?

```
C:\Users\Karl\tst\prices\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Users\Karl\AppData\Roaming\nvm\v10.11.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Karl\AppData\Roaming\nvm\v10.11.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
  win_delay_load_hook.cc
c:\users\karl\tst\prices\node_modules\nan\nan_maybe_43_inl.h(88): error C2039: 'ForceSet': is not a member of 'v8::Obje
ct' (compiling source file ..\src\bcrypt_node.cc) [C:\Users\Karl\tst\prices\node_modules\bcrypt\build\bcrypt_lib.vcxpro
j]
  c:\users\karl\.node-gyp\10.11.0\include\node\v8.h(3239): note: see declaration of 'v8::Object' (compiling source file
   ..\src\bcrypt_node.cc)
c:\users\karl\tst\prices\node_modules\nan\nan.h(816): warning C4996: 'node::MakeCallback': was declared deprecated (com
piling source file ..\src\bcrypt_node.cc) [C:\Users\Karl\tst\prices\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\karl\.node-gyp\10.11.0\include\node\node.h(174): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\bcrypt_node.cc)
c:\users\karl\tst\prices\node_modules\nan\nan.h(830): warning C4996: 'node::MakeCallback': was declared deprecated (com
piling source file ..\src\bcrypt_node.cc) [C:\Users\Karl\tst\prices\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\karl\.node-gyp\10.11.0\include\node\node.h(167): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\bcrypt_node.cc)
c:\users\karl\tst\prices\node_modules\nan\nan.h(844): warning C4996: 'node::MakeCallback': was declared deprecated (com
piling source file ..\src\bcrypt_node.cc) [C:\Users\Karl\tst\prices\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\karl\.node-gyp\10.11.0\include\node\node.h(160): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\bcrypt_node.cc)
c:\users\karl\tst\prices\node_modules\nan\nan.h(1457): warning C4996: 'node::MakeCallback': was declared deprecated (co
mpiling source file ..\src\bcrypt_node.cc) [C:\Users\Karl\tst\prices\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
  c:\users\karl\.node-gyp\10.11.0\include\node\node.h(174): note: see declaration of 'node::MakeCallback' (compiling so
  urce file ..\src\bcrypt_node.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Karl\AppData\Roaming\nvm\v10.11.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Karl\\AppData\\Roaming\\nvm\\v10.11.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Karl\tst\prices\node_modules\bcrypt
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@0.8.7 (node_modules\bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@0.8.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @resin/pinejs@8.4.1
updated 1 package and audited 921 packages in 27.038s
found 0 vulnerabilities
```

**Comment by kewp** [comment]
Looks like a Node v10 issue https://github.com/nodejs/nan/issues/763

Going to try 8.12.0 LTS...
